#!/bin/bash

alias vi='~/.local/bin/lvim'
alias vim='~/.local/bin/lvim'
alias grep='grep --color'
alias ls='ls --color -C'
alias ll='ls -larth --color'
alias sed='gsed'
alias be='bundle exec'
alias tmate-info="tmate display -p '#{tmate_ssh}'"
alias tmux-info="tmux lsk -N|more"

alias k='kubectl' && complete -F __start_kubectl k
alias kns='kubectl config set-context --current --namespace '
alias kf='kubectl create -f'
alias ks='kubectl run shell --image=ellerbrock/alpine-bash-curl-ssl -- tail -f /dev/null'

# url decode / encode
alias urldecode='python3 -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))"'
alias urlencode='python3 -c "import sys, urllib.parse as ul; print(ul.quote_plus(sys.argv[1]))"'
alias random='python -c "import string; import random; import sys; print(\"\".join((random.SystemRandom().choice(string.ascii_letters + string.digits)) for _ in range(int(sys.argv[1]))))"'
alias humantime='python -c "from datetime import datetime; import sys; print(datetime.fromtimestamp(int(sys.argv[1])))"'

# Display local ip address
alias localip="ipconfig getifaddr en0"

alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

_serve() {
  port="${1:-8888}"
  open "http://localhost:${port}/"
  python -m http.server "$port"
}
alias serve=_serve

alias fzf="fzf --height 40% --layout reverse --preview 'bat --style=numbers --color=always --line-range :500 {}'"

alias idea="open -na \"IntelliJ IDEA CE.app\" --args \"$*\""
alias finder='open -a Finder .'
