#!/bin/bash

# ::: Compiler flags :::

# This is required because `openssl` is keg-only in `brew`,
# see: `brew info openssl` for more information.
if [ "$(sysctl -n sysctl.proc_translated >/dev/null 2>&1)" = "1" ]; then
    brew_path="/usr/local"
else
    brew_path="/opt/homebrew"
fi
export LDFLAGS="-L${brew_path}/opt/openssl/lib"
export CPPFLAGS="-I${brew_path}/opt/openssl/include -I${brew_path}/opt/openjdk/include"
export PKG_CONFIG_PATH="${brew_path}/opt/openssl/lib/pkgconfig"
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

# ::: Path modifications :::

# prefer /usr/local before others. homebrew installs things in there. otherwise e.g. git would clash
export PATH="${brew_path}/bin:$PATH"

# homebrew installs some apps into /usr/local/sbin, e.g. openvpn
export PATH="${brew_path}/sbin:$PATH"

export PATH=~/.local/bin:$PATH

# golang
export GO111MODULE=auto
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:${brew_path}/opt/go/libexec/bin:$GOPATH/bin

# java
export JAVA_HOME=${brew_path}/opt/openjdk
export PATH="${JAVA_HOME}/bin:$PATH"

export PATH="${brew_path}/opt/openssl/bin:$PATH"
export PATH="${brew_path}/opt/openvpn/sbin:$PATH"


# ::: Package managers :::

# nvm (bad performance)
. "$HOME"/.nvmrc

# rbenv
eval "$(rbenv init -)"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# rvm
export PATH="$PATH:$HOME/.rvm/bin"                                    # make sure this is the last PATH variable change.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # Load RVM into a shell session *as a function*

# ::: History :::

export HISTCONTROL=ignoredups
export HISTIGNORE="$HISTIGNORE:ls:cd"
export HISTSIZE=950000                             # number of commands to remember in history
export HISTFILESIZE=950000                         # number of lines in history file
export PROMPT_COMMAND="history -a;$PROMPT_COMMAND" # always save history after every command


# ::: Others :::

# default editor
export EDITOR="$HOME"/.local/bin/lvim

# encoding
export LC_ALL=en_US.UTF-8

# vscode
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# flutter
export PATH=$HOME/workspace/flutter/bin:$PATH

# gem
export GEM_HOME=$HOME/.gem
export PATH=$HOME/.gem/bin:$PATH

# gpg
export GPG_TTY=$(tty)
eval "$(gpg-agent --daemon --allow-preset-passphrase > /dev/null 2>&1)"

# homebrew
export HOMEBREW_NO_ANALYTICS=1  # do not send statistics to homebrew

# git-duet
export GIT_DUET_GLOBAL=true
export GIT_DUET_ROTATE_AUTHOR=1
export GIT_DUET_CO_AUTHORED_BY=1

# dagger
export DO_NOT_TRACK=1
export DAGGER_NO_NAG=1
