#!/bin/bash

# ::: Compiler flags :::

# This is required because `openssl` is keg-only in `brew`,
# see: `brew info openssl` for more information.
if [ "$(sysctl -n sysctl.proc_translated)" = "1" ]; then
    bin_path="/usr/local/opt"
else
    bin_path="/opt/homebrew/opt"
fi
export LDFLAGS="-L${bin_path}/openssl/lib"
export CPPFLAGS="-I${bin_path}/openssl/include"
export PKG_CONFIG_PATH="${bin_path}/openssl/lib/pkgconfig"


# ::: Path modifications :::

# prefer /usr/local before others. homebrew installs things in there. otherwise e.g. git would clash
export PATH="/usr/local/bin:$PATH"

# homebrew installs some apps into /usr/local/sbin, e.g. openvpn
export PATH="/usr/local/sbin:$PATH"

export PATH=~/.local/bin:$PATH

# golang
export GO111MODULE=auto
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:${bin_path}/go/libexec/bin:$GOPATH/bin

# java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/sapmachine-11.jdk/Contents/Home
export PATH="$PATH:$JAVA_HOME/bin"

export PATH="${bin_path}/openssl/bin:$PATH"
export PATH="${bin_path}/python/libexec/bin:$PATH"
export PATH="${bin_path}/openvpn/sbin:$PATH"


# ::: Package managers :::

# nvm (commented out because of bad performance; sourced in selected projects only)
# . "$HOME/.nvmrc"

# rbenv
eval "$(rbenv init -)"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# pipenv
export PIPENV_PYTHON="$PYENV_ROOT/shims/python"

# rvm
export PATH="$PATH:$HOME/.rvm/bin"                                    # make sure this is the last PATH variable change.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # Load RVM into a shell session *as a function*

# ::: History :::

export HISTCONTROL=ignoredups
export HISTIGNORE="$HISTIGNORE:ls:cd"
export HISTSIZE=950000                             # number of commands to remember in history
export HISTFILESIZE=950000                         # number of lines in history file
export PROMPT_COMMAND="history -a;$PROMPT_COMMAND" # always save history after every command


# ::: Others :::

# default editor
export EDITOR=nvim

# encoding
export LC_ALL=en_US.UTF-8

# vscode
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# gpg
export GPG_TTY=$(tty)
eval "$(gpg-agent --daemon --allow-preset-passphrase > /dev/null 2>&1)"

# homebrew
export HOMEBREW_NO_ANALYTICS=1  # do not send statistics to homebrew

# lastpass
export LPASS_AGENT_TIMEOUT=28800  # logout from lpass after 8 hours

# git-duet
export GIT_DUET_GLOBAL=true
export GIT_DUET_ROTATE_AUTHOR=1
export GIT_DUET_CO_AUTHORED_BY=1