#!/usr/bin/env sh


pyclean() {
    find . | grep -E "(__pycache__|\.py[cod]$)" | xargs rm -rf
}

# cleans dangling docker containers and images
dclean() {
    docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
    docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
}

google() {
    open -na "Google Chrome" --args "https://www.google.com/search?q=$*"
}

stackoverflow() {
    open -na "Google Chrome" --args "https://www.google.com/search?q=site:stackoverflow.com $*"
}

