live_config_reload = true

[env]
  TERM = "xterm-256color"

[font]
  normal = { family = "Hack Nerd Font", style = "Regular" }
  size = 14

[window]
  padding = { x = 4, y = 2 }
  decorations = "None"
  opacity = 0.99
