#!/usr/bin/env bash

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    source $(brew --prefix)/etc/bash_completion
fi

source "$HOME/.bash_prompt"

source "$HOME/.shell/.aliases"
source "$HOME/.shell/.exports"
source "$HOME/.shell/.functions"

eval "$(direnv hook $0)"
