#!/bin/sh

export NVM_DIR="$HOME/.nvm"
[ -s "$(brew --prefix nvm)/nvm.sh" ] && . "$(brew --prefix nvm)"/nvm.sh > /dev/null 2>&1
[ -s "$(brew --prefix nvm)"/etc/bash_completion.d/nvm ] && . "$(brew --prefix nvm)"/etc/bash_completion.d/nvm