#!/usr/bin/env bash

set -e

mkdir ./tmp && cd tmp

# src: https://hci.rwth-aachen.de/usgermankeyboard
curl -O -L -J "https://hci.rwth-aachen.de/index.php?option=com_attachments&task=download&id=2764"

layout="USGerman Keyboard Layout 0.98 Retina"
unzip -o "$layout".zip

sudo rm -rf '/Library/Keyboard Layouts/'
sudo mkdir -p '/Library/Keyboard Layouts/'
sudo cp -R "$layout"/Roman.bundle '/Library/Keyboard Layouts/'

cd - && rm -rf ./tmp

# sudo cp ~/Library/Preferences/com.apple.HIToolbox.plist /Library/Preferences/
