#!/usr/bin/env bash

set -e

pip install --upgrade --no-deps --force-reinstall neovim
pip install --upgrade pynvim

npm install -g neovim

# gem install neovim

mkdir -p ~/.config
if [[ ! -d ~/.config/nvim ]]; then
  git clone https://github.com/luan/nvim ~/.config/nvim
fi
