#!/usr/bin/env bash

set -e

mkdir -p ./tmp && cd tmp

# src: https://hci.rwth-aachen.de/usgermankeyboard
curl -O -L -J "https://hci.rwth-aachen.de/get-attachment/2764?fallback=/files/migrated/files/USGerman-Keyboard-Layout-0.98-Retina.zip&filename=USGerman%20Keyboard%20Layout%200.98%20Retina.zip"

layout="USGerman Keyboard Layout 0.98 Retina"
unzip -o "$layout".zip

sudo rm -rf '/Library/Keyboard Layouts/'
sudo mkdir -p '/Library/Keyboard Layouts/'
sudo cp -R "$layout"/Roman.bundle '/Library/Keyboard Layouts/'

cd - && rm -rf ./tmp

# sudo cp ~/Library/Preferences/com.apple.HIToolbox.plist /Library/Preferences/
