#!/usr/bin/env bash

echo "Install Homebrew..."
if ! command -v brew &> /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

echo "Run the Brewfile..."
brew update
brew tap Homebrew/bundle
brew bundle --global
brew cleanup

echo "Install fuzzy finder"
$(brew --prefix)/opt/fzf/install --key-bindings --completion --no-fish --no-update-rc

echo "Install python..."
py_version="3.10.1"
if pyenv versions | grep -sq "$py_version"; then
  pyenv install "$py_version"
else
  echo "Python $py_version already installed"
  pyenv versions
fi

if pyenv which python | grep -sq "$py_version"; then
  pyenv global "$py_version"
else
  echo "Using global python version: $(python -V)"
fi

echo "Install cf CLI..."  # install via brew, once formula is M1 chip compatible
cd /tmp
curl -Ls "https://packages.cloudfoundry.org/stable?release=macosx64-binary&version=v7&source=github" | tar -zx
mv cf7 /usr/local/bin/cf
cf version
cd -

# echo "Install gems..."
# gem install bundler
# gem install neovim
