#!/usr/bin/env bash

echo "Install Homebrew..."
if ! command -v brew &> /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

echo "Run the Brewfile..."
brew update
brew tap homebrew/bundle
brew bundle --global
brew cleanup

echo "Install fuzzy finder"
$(brew --prefix fzf)/install --key-bindings --completion --no-fish --no-update-rc

echo "Install python..."
py_version="3.12.1"
if pyenv versions | grep -sq "$py_version"; then
  echo "Python $py_version already installed"
else
  pyenv install "$py_version"
fi
pyenv global "$py_version"

if [ ! -f $HOME/.pip/pip.conf ]; then
  [ ! -d $HOME/.pip ] && mkdir $HOME/.pip
  echo -e "[global]\nrequire-virtualenv=true\ntrusted-host=\n  pypi.python.org\n  pypi.org\n  files.pythonhosted.org" > $HOME/.pip/pip.conf
fi

echo "Install node..."
. "$(brew --prefix nvm)"/nvm.sh
nvm install 21
nvm use 21


# echo "Install gems..."
# gem install bundler
# gem install neovim
